name: push-scmscx.com

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    timeout-minutes: 30
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt, rust-src
          targets: wasm32-unknown-unknown

      - name: install wasm-bindgen
        run: cargo install wasm-bindgen-cli

      - name: work around Cargo.lock filetime not being updated..?
        run: touch Cargo.lock

      - name: scmscx.com docker image
        run: make push
